name: 'Deploy Firebase'
description: 'Deploy Firebase fullstack app'
author: 'Qiquan Lu'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  service_account_json:
    description: 'Content of your firebase credential json'
    required: true
    default: ''

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
